name = "otp-leonardo"
main = "_worker.js"
compatibility_date = "2024-04-01"

# Jika ingin menggunakan Custom Domain langsung
# [[routes]]
# pattern = "otpleo.rahmatpremium.cloud/*"
# custom_domain = true
